name: Deploy Web (Angular)

on:
  push:
    paths:
      - 'apps/client/**'
      - '.github/workflows/deploy-web.yml'
    branches: [ main ]

env:
  AWS_REGION: af-south-1
  S3_BUCKET: team7-todo-app
  CF_DIST_ID: YOUR_CLOUDFRONT_DISTRIBUTION_ID  # Replace this with your actual ID

permissions:
  id-token: write
  contents: read

jobs:
  deploy-angular:
    name: Build & Deploy Angular to S3
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apps/client

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_ARN }}
          role-session-name: deploy-angular-web
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build

      - name: Zip Angular build
        run: |
          cd dist
          zip -r angular-app.zip *
        working-directory: apps/client/dist

      - name: Upload to S3
        run: aws s3 cp dist/ s3://${{ env.S3_BUCKET }}/ --recursive --exclude "*" --include "*.html" --include "*.js" --include "*.css" --include "*.ico"

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.CF_DIST_ID }} \
            --paths "/*"
