name: Deploy API (Express)

on:
  workflow_run:
    workflows: ["Terraform"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies and build
        run: |
          cd apps/server
          npm i
          npm run build
          
      - name: Deploy via SSH
        run: |
          # Set up SSH key
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Copy files to EC2
          scp -o StrictHostKeyChecking=no -r apps/server/{package.json,package-lock.json,dist, prisma} ec2-user@${{ secrets.EC2_HOST }}:/var/www/api/
          
          # SSH commands to restart the app
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'ENDSSH'
          cd /var/www/api
          npm i
          npx prisma generate 
          pm2 restart ecosystem.config.js
          pm2 save
          ENDSSH